# Generated by Django 5.0.6 on 2024-06-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topproduct',
            name='popularity_rank',
        ),
        migrations.AddField(
            model_name='topproduct',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_id',
            field=models.URLField(),
        ),
    ]
