# Generated by Django 5.0.6 on 2024-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_topproduct_popularity_rank_topproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slogan',
            options={'verbose_name': 'Слоган', 'verbose_name_plural': 'Слоганы'},
        ),
        migrations.AlterModelOptions(
            name='topproduct',
            options={'verbose_name': 'Популярный продукт', 'verbose_name_plural': '5 популярных продуктов'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'verbose_name': 'Ютуб видео', 'verbose_name_plural': 'Ютуб видео'},
        ),
        migrations.AlterField(
            model_name='slogan',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текс слогана'),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фотокарточка'),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topproduct',
            name='price',
            field=models.PositiveIntegerField(default=100, verbose_name='Цена'),
        ),
    ]
