# Generated by Django 5.0.6 on 2024-06-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_myinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='SPORT',
            field=models.CharField(choices=[('Велосипеды', 'Велосипеды'), ('Самокаты', 'Самокаты'), ('Горнолыжный спорт', 'Горнолыжный спорт'), ('Бег', 'Бег')], max_length=20, null=True, verbose_name='Укажите вид спорта'),
        ),
    ]
